2024-09-26 20:32:34,194 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\OMEN\PycharmProjects\pythonProject\.venv\Мои задания\Модуль 12\tests_12_4\tests_12_4.py", line 25, in check
    func(self)
  File "C:\Users\OMEN\PycharmProjects\pythonProject\.venv\Мои задания\Модуль 12\tests_12_4\tests_12_4.py", line 43, in test_run
    self.r2 = rtwe.Runner(4526)
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\OMEN\PycharmProjects\pythonProject\.venv\Мои задания\Модуль 12\tests_12_4\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-09-26 20:32:34,195 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\OMEN\PycharmProjects\pythonProject\.venv\Мои задания\Модуль 12\tests_12_4\tests_12_4.py", line 15, in check
    func(self)
  File "C:\Users\OMEN\PycharmProjects\pythonProject\.venv\Мои задания\Модуль 12\tests_12_4\tests_12_4.py", line 34, in test_walk
    self.r1 = rtwe.Runner('Langsamer Karl', -5)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OMEN\PycharmProjects\pythonProject\.venv\Мои задания\Модуль 12\tests_12_4\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
